//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunKindergarten.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildrenTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChildrenTable()
        {
            this.ResultTable = new HashSet<ResultTable>();
        }
    
        public int PersonalNumberChildren { get; set; }
        public string SurnamesChildren { get; set; }
        public string NameChildren { get; set; }
        public string MiddlenameChildren { get; set; }
        public int GroupChildren { get; set; }
    
        public virtual GroupTables GroupTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultTable> ResultTable { get; set; }
    }
}
