//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunKindergarten.ModelFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SunDataBaseEntities : DbContext
    {
        public SunDataBaseEntities()
            : base("name=SunDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChildrenTable> ChildrenTable { get; set; }
        public virtual DbSet<EvaluationTables> EvaluationTables { get; set; }
        public virtual DbSet<EventTables> EventTables { get; set; }
        public virtual DbSet<GroupTables> GroupTables { get; set; }
        public virtual DbSet<ResultTable> ResultTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
